plugins = []
redirects = []

[functions]

  [functions."*"]

[build]
publish = "C:\\Users\\nuret\\OneDrive\\Desktop\\Esea Websitesi\\site"
publishOrigin = "default"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[[headers]]
for = "/*"

  [headers.values]
  X-Robots-Tag = "noindex, nofollow"